name: Controlling the Execution Flow
on: 
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                default: false

jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and Build
              run: echo "Linting and building project"
            
    deploy-nonprod:
        runs-on: ubuntu-latest
        # lint-build OK, unit-tests OK
        steps:
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod..."
            
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Running unit tests
              run: echo "Running tests..."
            - name: Failing tests
              if: ${{ inputs.pass-units-tests == false }}
              run: |
                   echo "Failing tests..."
                   exit 1

            
    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        # deploy-nonprod OK
        steps:
            - name: Running E2E tests
              run: echo "Running E2E tests..."
    load-tests:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        # deploy-nonprod OK
        steps:
            - name: Running load tests
              run: echo "Running load tests..."
    deploy-prod:
        runs-on: ubuntu-latest
        # e2e-tests OK, load-tests OK 
        needs: [ e2e-tests, load-tests ]
        steps:
            - name: Deploying to prod
              run: echo "Deploying to prod..."
            
        
